plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - Readme.md
logo: /^images/logo.png
theme: null
title: bl2parts
twitter:
  card: summary
url: https://bl2.parts

defaults:
  - scope:
      path: ""
    values:
      description: BL2/TPS Part Guides
      image:
        path: /^images/logo.png
        width: 200
        height: 200
  - scope:
      path: "*/all_parts/index.md"
    values:
      description: All parts, including uniques, and the exact bonuses they give.
  - scope:
      path: "*/zoom/index.md"
    values:
      description: Just how far each sight zooms you in.
